env:
  browser: true
  es6: true
  webextensions: true

extends:
  - eslint:recommended

globals:
  KintoClient: false
  Quill: false
  Jose: false
  JoseJWE: false
  TestPilotGA: false
  FxaCrypto: false

root: true

rules:
  eqeqeq: error
  linebreak-style: [error, unix]
  no-console: warn
  no-var: error
  prefer-const: error
  quotes: [error, single]
  semi: [error, always]
